stop()
- [ ] NOTE(2016-07-21): this is superseded by the handwritten abstract file 2_abstract.md
---
title: "2_abstract"
author: "Steve Harris"
date:	"30 Dec 2015"
output: md_document
---
```{r include=FALSE, echo=FALSE}
source("5_results_01start.R")
source("2_abstract_prep.R")
```
# Abstract

Please note that as of 24 October 2015, The BMJ underwent a substantial print redesign. We have dispensed with the Pico summary, and now use restructured abstracts that will appear in the print issue only. Please note that the definitive, online version of the full length article will still have abstracts structured as set out in the guidelines below.

With the new print abstract structure, we hope to merge the best components of the Pico and the online abstract to present the information in a succinct and readable format. We will update this section in due course, but for more details please see this editorial.

Please ensure that the structured abstract is as complete, accurate, and clear as possible—but not unnecessarily long—and has been approved by all authors. We may screen original research articles by reading only the abstract. For randomised controlled trials please provide all the information required for the CONSORT extension for abstracts.

> Please note the general rules for abstracts in The BMJ:
> 
> Abstracts should be 250- 300 words long: you may need up to 400 words, however, for a CONSORT or PRISMA style abstract. MEDLINE can now handle up to 600 words
> Use active voice but avoid “we did” or “we found”.
> Numbers over 10 do not need spelling out at the start of sentences.
> Sentences starting with a number do not require a capital letter.
> P values should always be accompanied by supporting data, and denominators should be given for percentages.
> Abstracts do not need references.
> If the standard headings do not suit the type of study, please substitute something sensible, such as "population" as a heading instead of "participants" in an economics article. Please do not simply delete the heading.
> 
> For standard original research articles please provide the following headings and information (for RCTs please add the trial registration details - but there is no need to provide the additional subheadings which are used in the CONSORT statement on abstracts, as long as you include all the required information, and the same applies to the PRISMA statement):
> 
> Objectives - a clear statement of the main aim of the study and the major hypothesis tested or research question posed
> Design - including factors such as prospective, randomisation, blinding, placebo control, case control, crossover, criterion standards for diagnostic tests, etc.
> Setting - include the level of care, eg primary, secondary; number of participating centres. Be general rather than give the name of the specific centre, but give the geographical location if this is important.
> Participants (instead of patients or subjects) - numbers entering and completing the study, sex, and ethnic group if appropriate. Give clear definitions of how selected, entry and exclusion criteria.
> Interventions - what, how, when and for how long. This heading can be deleted if there were no interventions but should normally be included for randomised controlled trials, crossover trials, and before and after studies.
> Main outcome measures - those planned in the protocol, those finally measured (if different, explain why).
> Results - main results with (for quantitative studies) 95% confidence intervals and, where appropriate, the exact level of statistical significance and the number need to treat/harm. Whenever possible, state absolute rather than relative risks.
> Conclusions - primary conclusions and their implications, suggesting areas for further research if appropriate. Do not go beyond the data in the article. Conclusions are important because this is often the only part that readers look at.
> Trial registration - registry and number (for clinical trials and, if available, for observational studies and systematic reviews).
> Please note that confidence intervals should be written in the format (15 to 27) within parentheses, using the word "to" rather than a hyphen.

## Objectives 

To describe the provision, the timeliness of critical care, and the mortality for deteriorating ward patients, and the effect of critical care bed occupancy assessed with different

## Design 

Prospective observational cohort study

## Setting 

48 NHS hospitals

## Participants

15158 adult ward patients referred to, and assessed at the bedside by critical care during 2010-11

## Main outcome measures 

Provision and timeliness of critical care, and mortality up to one year

## Results 

15158 ward patients were assessed by critical care. 5164 (34%) patients were in organ failure, but only 870 (6%) were already in receipt of organ support. 6759 (45%) were in the highest NEWS risk class giving an incidence of 17 NEWS high risk referrals was per hospital per month. The critical care unit was full at the time of 1198 (8%) assessments.

2141 (14%) patients with treatment limitation orders were declined critical care. Of the 13017 patients remaining, 4976 (38%) were recommended for critical care, and 3375 (68%) were immediately offered admission with a median delay to admission of 2 hours (IQR 1 to 4). The 1601 (32%) patients recommended for, but not immediately offered, critical care comprised 1021 (64%) who were admitted later  (median delay 12 hours [IQR 5 to 29]), and 179 (11%) patients who died without admission. Decision making varied by patient subgroup (OR 0.60 [95%CI 0.53 to 0.69] for immediate admission if 80 years or older), and by hospital (median inter-hospital OR 2.11, 95% 1.81 to 2.42). Without treatment limits, 7-day, 90-day, and 1-year mortalities were 14%, 30%, and 39% (1827, 3935, and 5068 deaths respectively). Mortality occured early
with 964 of first week deaths (53%) within two days. After adjustment for patient specific risks, survival still varied between hospitals (median interhospital hazard ratio of 1.29 [95%CI, 1.22--1.35]).

Patients assessed when critical care was full were less likely to be offered admission  (OR 0.72 \[95%CI 0.59--0.88\]), and less likely to be admitted promptly (OR 0.27 \[95%CI 0.19--0.37\]). Increasing occupancy was associated with greater physiological deterioration pending admission (p=0.01). We could
not exclude an effect of occupancy on 90-day survival (HR 1.07, 95%CI
1.00--1.15).

## Conclusions 

Deteriorating ward patients referred to critical care are vulnerable with a high initial mortality. Despite clinical recommendation for admission a substantial minority die without admission. High critical care occupancy both prejudices and delays admission.





## Trial registration 

## Background

Identifying and responding to deterioration among ward patients includes early access to critical care. However, critical care provision in the NHS is constrained, and the effects of this on delay to critical care admission, and patient outcomes are poorly understood.

## Methods

We conducted a prospective cohort study of consecutive deteriorating ward patients referred to critical care in `r tt$sites` NHS hospitals (1 November 2010 --- 31 December 2011). We recorded both the assessor's recommendation for critical care, and the decision to admit. Admissions to critical care within one week, and deaths within one year were defined by linking to national registries. Incidence models were stratified by the NHS National Early Warning Score (NEWS) risk class, and used generalised estimating equations. Decision making and survival were modelled with random effects for the hospital using logistic regression and proportional hazards models respectively. 

## Findings

Critical care teams assessed `r tt$patients` patients of whom `r tt$news_high$n` (`r tt$news_high$p`) were in the highest NEWS risk class giving an incidence of 17 NEWS high risk patients (95\%CI 17--18) per hospital per month. `r odys$n[2]` (`r odys$p[2]`) patients were already in established organ failure. Sepsis was reported in `r sepsis$n[2]` (`r sepsis$p[2]`) patients.

`r tt$rxlimits$n[2]` (`r tt$rxlimits$p[2]`) patients with treatment limitation orders were declined critical care. 7-day, 90-day, and 1-year mortalities were `r tt$rxlimits_dead7$p[2]`, `r tt$rxlimits_dead90$p[2]`, and `r tt$rxlimits_dead1y$p[2]` respectively.

Of the remainder, the bedside assessor recommended `r tt$reco$n[2]` (`r tt$reco$p[2]`) to critical care. `r tt$reco_accept$n[2]` (`r tt$reco_accept$p[2]`) were immediately accepted. The median delay between assessment and admission was `r icu.delay$q50` hours (IQR `r icu.delay$iqr`).  Patients over 80 years were less likely to be accepted (OR 0.60 95\%CI 0.53--0.69). Despite adjustment for patient specific risk factors, decision making varied markedly between hospitals (median inter-hospital OR 2.11, 95\%1.81--2.42).

Of the `r tt$reco_accept$n[1]` (`r tt$reco_accept$p[1]`) patients recommended but initially refused, `r tt$reco_late$n[2]` (`r tt$reco_late$p[2]`) were admitted later with a median additional delay of `r delay.by.accept.reco$estimate` hours (IQR `r delay.by.accept.reco$lower`--`r delay.by.accept.reco$upper`). A further `r tt$reco_d7ward$n[2]` (`r  tt$reco_d7ward$p[2]`) patients recommended and refused died without admission.

Excluding patients with treatment limits, 7-day, 90-day, and 1-year mortalities were `r tt$dead7$p[2]`, `r tt$dead90$p[2]`, and `r tt$dead1y$p[2]` respectively. Mortality occurred early with `r tt$dead7.d2$n[2]` of first week deaths (`r tt$dead7.d2$p[2]`) within two days. Survival also varied between hospitals with a median inter-hospital hazard ratio of 1.29 (95%CI, 1.22--1.35).

The critical care unit was full at the time of `r tt$full$n` (`r tt$full$p`) assessments. The patients concerned were less likely to be accepted to critical care (OR 0.72 [95%CI 0.59--0.88]), and less likely to be admitted promptly (OR 0.27 [95%CI 0.19--0.37]). Increasing occupancy was associated with greater physiological deterioration pending admission (p=0.01). We could not exclude an effect of occupancy on 90-day survival (HR 1.07, 95%CI 1.00–-1.15).

## Conclusion

Deteriorating ward patients referred to critical care are vulnerable with a high initial mortality. Despite clinical recommendation for admission a substantial minority die without admission. High critical care occupancy both prejudices and delays admission.

## Funding

Wellcome Trust, NIHR Service Support Costs, and the Intensive Care National Audit & Research Centre

- [ ] TODO(2016-06-04): A registration number and name of register for any study type, if registered—in the last line of the structured abstract. We are keen to promote registration for observational studies and systematic reviews.

