#! python
# Build tables
# - [ ] TODO(2015-11-28): add generator for tb_table1_all.R


def build(ctx):

    # Model APS for ward patients (supp table)
    # ----------------------------------------
    ctx(
        name='tb_model_aps',
        features='run_r_script',
        source='tb_model_aps.R',
        target=[
            ctx.path_to(ctx, 'TABLES', 'tb_model_icnarc_aps.xlsx')
            ],
        deps=[
            ctx.path_to(ctx, 'DATA', 'paper-spotepi.RData')
        ]
    )
